name: Deploy website on push
on:
  pull_request:
    types:
      - closed
    branches: 
      - main
  push:
    branches:
      - main
jobs:
  web-deploy:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /el-pollo-loco/